[[language]]
name = "swift"
auto-format = true
formatter = { command = "xcrun", args = ["swift-format", "format", "-"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-bn", "-ci", "-sr"] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

[[language]]
name = "json"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
