#!/bin/bash
if [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi

case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) PATH="$HOME/.local/bin:$PATH" ;;
esac
export PATH

case $- in
  *i*)
    if [ -f "$HOME/.bashrc" ]; then
      . "$HOME/.bashrc"
    fi
    ;;
esac
