#!/bin/bash
case $- in
  *i*) ;;
  *) return ;;
esac

if [ -f "$HOME/.bashrc.pre-scrubs" ]; then
  . "$HOME/.bashrc.pre-scrubs"
fi

case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) PATH="$HOME/.local/bin:$PATH" ;;
esac
export PATH
