#!/bin/sh
# SCRUBS_PROFILE

if [ -f "$HOME/.profile.pre-scrubs" ]; then
  . "$HOME/.profile.pre-scrubs"
fi

case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) PATH="$HOME/.local/bin:$PATH" ;;
esac
export PATH
