name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  Lint:
    runs-on: macos-26
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2026.5.15
          github_token: ${{ github.token }}
      - run: just fmt-check

  Test:
    runs-on: macos-26
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Ensure Homebrew
        shell: zsh {0}
        run: |
          if ! command -v brew >/dev/null 2>&1; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
      - run: brew bundle --file="${{ github.workspace }}/home/Brewfile.ci"
        shell: zsh {0}
      - run: mise install
        shell: zsh {0}
        env:
          MISE_GITHUB_TOKEN: ${{ github.token }}
      - run: ${{ github.workspace }}/setup.sh
        shell: zsh {0}
        env:
          VIRTUAL_HOME: ${{ github.workspace }}/home
      - run: nu ${{ github.workspace }}/scripts/configure-apps.nu
        shell: zsh {0}
      - run: just helix-theme-build
        shell: zsh {0}
